language: node_js
node_js:
  - '11'
cache:
  directories:
    - node_modules
matrix:
  include:
  - os: osx
addons:
  apt:
    packages:
      - zip
script:
   - npm run build
before_deploy:
  - export TRAVIS_TAG="Build_$(date +'%Y.%m.%d-%H%M')"
deploy:
  provider: releases
  name: ${TRAVIS_TAG}
  skip_cleanup: true
  api_key:
    secure: iNCxgz2jlVNo12byTdYUv7OXxXL5PfRUt9T6AXBkyBJHGAD01qU1MINhPCxqmlgoWSjbGYsDR0bgnlfEiYqQB4fpxN/5KwA1BeWvHx1iox0yNm1ECg1fOUo0ksH0zoeqVceJyfNFSAhdlipdVumezGHsdG6qEOjM1gpLs/IcfdAvxnD/4hGiYIMbkslIvJ8DkroXIU5JEpsCNSlzjgGI2/hhhzudhwGCKlv+ydECtNn3k5giJN1wno1I3+hfr3DwcbPN5b2mMhJKFQ2yppIxXM0ZjiS3hsJ7exhuNDsHbtdtk4sbKJxjKBVEl9yk0YSLpH+T22fEZbC//TlTgcVYT23K/d4OycA5Lzl2Cc9gOQsqp4+GhWciYSdHP75ZpDwB2W4anIIpx0MZi2XR/cGnTm5N5mTEMwQuDFtBRaWR7jBRw947hQX2vKGDEN2u013qAtVMonwuh5CP7ZNk1+AvZDh0Qsg/sCucX0O4ZCVeudTwgGawwvgWDLwny3X8EycX1z4+7wuktTMIB4WMnjGCx863w1SHOSXsdYM4VBuUA86x2v3DCdKpsruyxNdR68ghmGMG4erC+7OLNOpKxBaaqG8mWB9OS6Z6rKQWMgmqgrubaAWqqWhOk6+jAO7tMQXEbSCENa3z2r5W8Cm+VTVM6FBNlkrBZaI35rm1fn7uv8E=
  file: test.app
  on:
    tags: false
    repo: jrrombaldo/cloud-enc
    branch: master
