dist: trusty
language: node_js
node_js: 13


jobs:
  include:
    - os: linux
    - os: osx
install:
    - |
      set -x
      set -euo pipefail
      npm ci
cache:
  directories:
    - "node_modules"
  