dist: trusty
language: node_js
node_js: 13


jobs:
  include:
    - os: linux
    - os: osx
cache:
  directories:
    - "node_modules"
install:
  - |
  if [ $TRAVIS_OS_NAME = 'osx' ]; then
    echo "MAC"
  fi

  if [ $TRAVIS_OS_NAME = 'linux' ]; then
    echo "llinux"
  fi
  