dist: trusty
language: node_js
node_js: 13


jobs:
  include:
    - os: linux
      env: LABEL=linux
    - os: osx
      env: LABEL=osx
cache:
  directories:
    - "node_modules"
before_install:
  - |
    if [ $TRAVIS_OS_NAME = 'osx' ]; then
      echo "MAC"
    fi

    if [ $TRAVIS_OS_NAME = 'linux' ]; then
      echo "llinux"
    fi