dist: trusty
language: node_js
node_js: 13

jobs:
  include:
    - os: linux
    - os: osx
before_install:
    - |
      set -x
      set -euo pipefail
      if [ "$TRAVIS_OS_NAME" = "osx" ]; then 
        brew cask install osxfuse;
        brew install encfs;
        sudo security unlock-keychain -u;
      fi
      if [ "$TRAVIS_OS_NAME" = "linux" ]; then 
        sudo apt update
        sudo apt install encfs -y
      fi

install:
    - npm install
    - npm run build
    - npm run test
script:
    - npm make
    - ls -larthR

# jobs:
#     include:
#         before_install:
#             - |
#                 set -x
#                 set -euo pipefail
#                 brew update
#                 brew cask install osxfuse
#                 brew install encfs
#                 sudo security unlock-keychain
#         script:
#             - |
#                 npm install
#                 npm run build
#                 npm run test
#                 npm run make
#                 ls -larthR

# jobs:    
#     include:
#     - name: ubuntu
#         # os: linux
#         # dist: bionic
#         before_install:
#             - set -euo pipefail
#             - set -x
#             - sudo apt install encfs -y
    #         install:
    #             - |
    #                 npm install
    #                 npm run build
    #                 npm run test
    #                 npm run make
    #                 ls -larthR

        
    #     - name: mac 10.12
    #             os: osx
    #             osx_image: xcode9
    #             before_install:
    #                 - |
    #                 set -x
    #                 set -euo pipefail
    #                 brew update
    #                 brew cask install osxfuse
    #                 brew install encfs
    #                 sudo security unlock-keychain
    #             install:
    #                 - |
    #                     npm install
    #                     npm run build
    #                     npm run test
    #                     npm run make
    #                     ls -larthR
