name: "Cryptobox CI"

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
env:
  BRANCH: ${{ github.ref }}

jobs:
     
    
  Linting:
    runs-on: ubuntu-latest
    if: false
    steps:
      - uses: actions/checkout@v2
      - run: set -xeuo pipefail
      - name: linting for branch => ${{ github.ref }}
        run: |
          echo "linting the app"
          npm ci
          npm run lint || true # lint is currently failling


  GitHub-Testing:
    if: false
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        os: [ubuntu-18.04, ubuntu-latest, macos, macos-latest]
        node-version: [12.x, 13.x]
    steps:
      - uses: actions/checkout@v1
      # - name: Using node version ${{ matrix.node-version }}
        # uses: actions/setup-node@v1
      #   with:
      #     node-version: ${{ matrix.node-version }}

      - run: set -xeuo pipefail
      - name: Test on ${{ matrix.target }}
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt install encfs -y
          npm ci
          npm test

      - name: Test on ${{ matrix.target }}
        # if: startsWith(matrix.os, 'macos')
        run: |
          /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
          brew cask install osxfuse
          brew install encfs
          sudo security unlock-keychain -u
          npm ci
          npm run make
      


  Travis-Testing:
    runs-on: ubuntu-latest
    if: true
    env:
      BRANCH_FULL: ${{ github.ref }}
      TRAVIS_TOKEN: ${{ secrets.TRAVIS_TOKEN }}
    steps:
      - run: set -xeuo pipefail
      - run: echo ::set-env name=BRANCH::$(basename $BRANCH)
      - uses: actions/checkout@v2
      # - uses: actions/setup-python@v1
      #   with:
      #     python-version: '3.x' # Semantic version range syntax or exact version of a Python version
      #     architecture: 'x64' # Optional - x64 or x86, defaults to x64
      - name: Testing on Travis for branch => ${{ github.ref }}
        run: |
          echo ${{ matrix.target }}
          cd ./build
          pip install -r requirements.txt
          # python3 travis.py
      # - run: |
      #     echo "Installing Travis "
      #     set -eo pipefail
      #     sudo apt install ruby-dev libffi-dev make gcc &&  sudo gem install travis
      #     travis --version
      #     travis login --pro --github-token ${{ secrets.TRAVIS_TOKEN }}
      #     echo ::set-env name=TRAVIS_TOKEN_API::$(travis token --pro)





  Building-Artifacts:
    if: false
    runs-on: ${{matrix.os}}
    # needs:  [Linting, Travis-Testing]
    strategy:
      fail-fast: true # do not generate artefacts if any other job failed
      max-parallel: 10
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - run: set -xeuo pipefail
      - name: BUILDING for branch => ${{ github.ref }}
        run: |
          echo "building artifacts"
          uname -a
          npm ci
          npm run make

      - name: uploading artefacts
        # if: startsWith(matrix.os, 'ubuntu')
        uses: actions/upload-artifact@v2
        with:
          name: release
          # here https://github.com/actions/upload-artifact it does mention the pattern follows https://facelessuser.github.io/wcmatch/glob/ but the following links does not work
          # path: release/**/[Cc]rypto[Bb]ox.*
          # path: release/cryptobox*.*(dmg|app|deb|rpm|tar.gz) 	
          path: release/cryptobox*


  Create-Release:
    runs-on: ubuntu-latest
    # if: ${{ contains(['master', 'dev'], github.ref}}
#     needs: [Building-Artifacts]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - run: echo $BRANCH
#       - name: Create release
#         id: create_release
#         uses: actions/create-release@v1
#         with:
#             tag_name: ${{ github.run_number }}
#             release_name: Release ${{ github.run_number }}
#             draft: true
#             prerelease: true
#             body: |
#               testing releases through the pipelines

    
    


  Upload-Release:
    if: false
    runs-on: ubuntu-latest
    needs: [Create-Release]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: true # do not generate artefacts if any other job failed
      max-parallel: 10
      matrix:
        # flavour: [".dmg", ".tar.gz", "-ia32.tar.gz", "_i386.deb", "_amd64.deb", ".i686.rpm", ".x86_64.rpm"]
        flavour : ["cryptobox-0.0.1.tar.gz", "cryptobox-0.0.1-ia32.tar.gz", "cryptobox_0.0.1_i386.deb", "cryptobox_0.0.1_amd64.deb", "cryptobox-0.0.1.i686.rpm", "cryptobox-0.0.1.x86_64.rpm"]
    
    steps:
      - name: download CLI image
        uses: actions/download-artifact@v1
        with:
          name: release

      - run: ls -larthR
      - run: echo ::set-env PRODUCT_NAME=$(node -p "require('./package.json').productName")
      - run: echo ::set-env PRODUCT_VERSION=$(node -p "require('./package.json').productName")


      - name: Upload ${{matrix.flavour}}
        uses: actions/upload-release-asset@v1
        with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: release/${{ matrix.flavour }}
            asset_name: ${{ matrix.flavour }}
            asset_content_type: application/zip

      # - name: Upload RPM x86
      #   uses: actions/upload-release-asset@v1
      #   with:
      #       upload_url: ${{ steps.create_release.outputs.upload_url }}
      #       asset_path: release/$PRODUCT_NAME-$PRODUCT_VERSION.i686.rpm
      #       asset_name: cryptobox-$PRODUCT_VERSION.i686.rpm
      #       asset_content_type: application/zip

      # - name: Upload RPM x64
      #   uses: actions/upload-release-asset@v1
      #   with:
      #       upload_url: ${{ steps.create_release.outputs.upload_url }}
      #       asset_path: release/cryptobox-$PRODUCT_VERSION.x86_64.rpm
      #       asset_name: cryptobox-$PRODUCT_VERSION.x86_64.rpm
      #       asset_content_type: application/zip
    
      # - name: Upload DEB x86
      #   uses: actions/upload-release-asset@v1
      #   with:
      #       upload_url: ${{ steps.create_release.outputs.upload_url }}
      #       asset_path: release/${{PRODUCT_NAME}}-${{PRODUCT_VERSION}}.dmg
      #       asset_name: ${{PRODUCT_NAME}}-${{PRODUCT_VERSION}}.dmg
      #       asset_content_type: application/zip

      # - name: Upload DEB x64
      #   uses: actions/upload-release-asset@v1
      #   with:
      #       upload_url: ${{ steps.create_release.outputs.upload_url }}
      #       asset_path: release/cryptobox-$PRODUCT_VERSION_amd64.deb
      #       asset_name: cryptobox-$PRODUCT_VERSION_amd64.deb
      #       asset_content_type: application/zip
