# https://levelup.gitconnected.com/how-to-manually-trigger-a-github-actions-workflow-4712542f1960

name: CryptoBox Releases
on:
  workflow_dispatch:
    inputs:
      ref:
        description: the branch, tag or SHA to checkout
        required: true
      draft:
        description: is it a draft?
        default: true
        required: true
      pre-release:
        description: is it pre-release
        default: true
        required: true
jobs:
  echoing-input:
    name: printing the inputs
    runs-on: ubuntu-latest
    steps:
      - name: printing inputs
        run: |
          echo " commit ${{ github.event.inputs.ref }} "
          echo " draft ${{ github.event.inputs.draft }} "
          echo " pre-release ${{ github.event.inputs.pre-release }} "
  checkingout:
    runs-on: ubuntu-latest
    steps:
      - name: checkout ${{ github.event.inputs.ref }}
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.ref }} "
