name: "Cryptobox CI"
on:
    push:
      branches:
        - 'feature-actions'
jobs:
    "Test-on-Travis":
      runs-on: ubuntu-latest
      env:
        BRANCH_FULL: ${{ github.ref }}
        TRAVIS_TOKEN: ${{ secrets.TRAVIS_TOKEN }}

      steps:
        - run: echo ::set-env name=BRANCH::$(basename $BRANCH_FULL)
        - run: echo "Building on branch $BRANCH and $GITHUB_REF_NAME"

        - run: |
            echo "Installing Travis "
            set -eo pipefail
            sudo apt install ruby-dev libffi-dev make gcc &&  sudo gem install travis
            travis --version
            travis login --pro --github-token ${{ secrets.TRAVIS_TOKEN }}
            travis token --pro
            echo ::set-env name=TRAVIS_TOKEN_API::$(travis token --pro)
            echo "travis=$TRAVIS_TOKEN_API"
            
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v1
          with:
            python-version: '3.x' # Semantic version range syntax or exact version of a Python version
            architecture: 'x64' # Optional - x64 or x86, defaults to x64
        - name: trigger Travis on $BRANCH
          run: |
            cd ./build
            pip install -r requirements.txt
            python3 travis.py
