name: "Test on Travis"
on:
    push:
      branches:
        - 'feature-actions'
jobs:
    test:
      runs-on: ubuntu-latest
      env:
        BRANCH: ${{ github.ref }}
      steps:
        - run:   echo ::set-env name=GITHUB_REF_NAME::$(echo "$GITHUB_REF_NAME" | awk -F / '{print $2}')
          shell: bash
        - run: |
                echo $GITHUB_REF_NAME
                BRANCH2=$(basename $BRANCH)
                echo "$BRANCH2"
          shell: bash
          
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v1
          with:
            python-version: '3.x' # Semantic version range syntax or exact version of a Python version
            architecture: 'x64' # Optional - x64 or x86, defaults to x64
        - name: trigger Travis on $BRANCH
          run: |
            BRANCH=$(basename $BRANCH)
            echo $BRANCH
            cd ./build
            pip install -r requirements.txt
            python3 travis.py
