name: "run Travis"
on:
    push:
      branches:
        - 'feature-actions'
jobs:
    test:
      runs-on: ubuntu-latest
      env:
        BRANCH: ${{ github.ref }}
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v1
          with:
            python-version: '3.x' # Semantic version range syntax or exact version of a Python version
            architecture: 'x64' # Optional - x64 or x86, defaults to x64
        - name: trigger Travis
          run: |
            BRANCH =  basename $BRANCH
            echo $BRANCH
            cd ./build
            pip install -r requirements.txt
            python3 travis.py