on:
  schedule:
    - cron:  '0 16 * * FRI'
  push:
    branches:
    - dev
    - master
  pull_request:
    branches:
    - dev
    - master

jobs:
  testing:
    name: Testing on 

    runs-on:  ${{ matrix.platform}}

    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        platform: [ubuntu-16.04, ubuntu-18.04, ubuntu-latest, macos, macos-latest]
        node-version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Using node version ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Prepare linux
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt install encfs -y
          mkdir -p ~/cryptobox/ && echo "12345" > ~/cryptobox/pass.txt
          
      - name: Prepare MAC
        if: matrix.platform == 'macos-latest'
        run: |
          /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
          brew cask install osxfuse
          brew install encfs


      - name: Running the tests with node ${{ matrix.node-version }} and ${{ matrix.platform}}
        run: |
          npm ci
          npm test
