on:
  schedule:
    - cron:  '*/5 * * * *'
  push:
    branches:
    - dev
    - master
  pull_request:
    branches:
    - dev
    - master

jobs:
  testing:
    name: Testing on 

    runs-on:  ${{ matrix.platform}}

    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        platform: [ubuntu-latest, macos-latest]
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Using node version ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Prepare linux
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt install encfs -y
          mkdir -p ~/cryptobox/ && echo "12345" > ~/cryptobox/pass.txt
          
          
      - name: Prepare MAC
        if: matrix.platform == 'macos-latest'
        uses: artemnovichkov/action-homebrew@0.1.0


      - name: Running the tests with node ${{ matrix.node-version }} and ${{ matrix.platform}}
        run: |
          
          npm ci
          npm test
