on:
    schedule:
      - cron:  '* */5 * * *'
    push:
      branches:
        - '*'
    pull_request:
      branches:
        - '*'
  
jobs:
    testing:
      name: Testing on 
  
      runs-on:  ${{ matrix.os}}
  
      strategy:
        fail-fast: false
        max-parallel: 10
        matrix:
          os: [ubuntu-latest, macos-latest]
          node-version: [13.x]
  
      steps:
        - uses: actions/checkout@v1
        
        - name: Using node version ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}
            
        - name: prepare environment
          uses: ./.github/workflows/prepare-environments

        - name: Running the tests with node ${{ matrix.node-version }} and ${{ matrix.os}}
          run: |
            npm ci
            npm build
            npm test
  
